package com.cfox.greendaomultdb.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cfox.greendaomultdb.db.table.TableAa;
import com.cfox.greendaomultdb.db.table.TableAb;
import com.cfox.greendaomultdb.db.table.TableBa;
import com.cfox.greendaomultdb.db.table.TableBb;

import com.cfox.greendaomultdb.db.dao.TableAaDao;
import com.cfox.greendaomultdb.db.dao.TableAbDao;
import com.cfox.greendaomultdb.db.dao.TableBaDao;
import com.cfox.greendaomultdb.db.dao.TableBbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableAaDaoConfig;
    private final DaoConfig tableAbDaoConfig;
    private final DaoConfig tableBaDaoConfig;
    private final DaoConfig tableBbDaoConfig;

    private final TableAaDao tableAaDao;
    private final TableAbDao tableAbDao;
    private final TableBaDao tableBaDao;
    private final TableBbDao tableBbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableAaDaoConfig = daoConfigMap.get(TableAaDao.class).clone();
        tableAaDaoConfig.initIdentityScope(type);

        tableAbDaoConfig = daoConfigMap.get(TableAbDao.class).clone();
        tableAbDaoConfig.initIdentityScope(type);

        tableBaDaoConfig = daoConfigMap.get(TableBaDao.class).clone();
        tableBaDaoConfig.initIdentityScope(type);

        tableBbDaoConfig = daoConfigMap.get(TableBbDao.class).clone();
        tableBbDaoConfig.initIdentityScope(type);

        tableAaDao = new TableAaDao(tableAaDaoConfig, this);
        tableAbDao = new TableAbDao(tableAbDaoConfig, this);
        tableBaDao = new TableBaDao(tableBaDaoConfig, this);
        tableBbDao = new TableBbDao(tableBbDaoConfig, this);

        registerDao(TableAa.class, tableAaDao);
        registerDao(TableAb.class, tableAbDao);
        registerDao(TableBa.class, tableBaDao);
        registerDao(TableBb.class, tableBbDao);
    }
    
    public void clear() {
        tableAaDaoConfig.clearIdentityScope();
        tableAbDaoConfig.clearIdentityScope();
        tableBaDaoConfig.clearIdentityScope();
        tableBbDaoConfig.clearIdentityScope();
    }

    public TableAaDao getTableAaDao() {
        return tableAaDao;
    }

    public TableAbDao getTableAbDao() {
        return tableAbDao;
    }

    public TableBaDao getTableBaDao() {
        return tableBaDao;
    }

    public TableBbDao getTableBbDao() {
        return tableBbDao;
    }

}
